app:
  config:
    id: 'my-app'
    log_level: 'WARNING'
    collect_metrics: true
    name: 'my-app'

llm:
  provider: openai
  config:
    model: 'gpt-4'
    temperature: 0.5
    max_tokens: 1000
    top_p: 1
    stream: false

vectordb:
  provider: opensearch
  config:
    opensearch_url: 'https://localhost:9200'
    http_auth:
      - admin
      - admin
    vector_dimension: 1536
#    vector_dimension: 1024
    collection_name: 'my-app'
    use_ssl: false
    verify_certs: false

embedder:
  provider: openai
  config:
    model: 'text-embedding-ada-002'
#    deployment_name: 'my-app'

#embedder:
#  provider: huggingface
#  config:
#    model: 'moka-ai/m3e-large'